name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image with cache
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: osc-midi-bridge:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Run tests
      run: make test
    
    - name: Run integration tests
      run: make integration-test
    
    - name: Run linter
      run: make vet
    
    - name: Check formatting
      run: |
        make fmt
        git diff --exit-code || (echo "Code not formatted. Run 'make fmt'" && exit 1)

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build binary with cached Docker
      run: make build
    
    - name: Upload binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: osc-midi-bridge
        path: osc-midi-bridge