name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: make docker-build
    
    - name: Run tests
      run: make test
    
    - name: Run integration tests
      run: make integration-test
    
    - name: Run linter
      run: make vet
    
    - name: Check formatting
      run: |
        make fmt
        git diff --exit-code || (echo "Code not formatted. Run 'make fmt'" && exit 1)

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build binary
      run: make build
    
    - name: Upload binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: osc-midi-bridge
        path: osc-midi-bridge